# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ycpcYnJFXd_P28M4VIypTQ2NaETf8Hz

**Pandas**

⚡**there are 2 data structures in pandas** 
      

1.   **Series**
2.   **DataFrames**  ⚡

Series
--> one dimensional array holding data of any type
"""

import pandas as pd

mydata = ['s','a','m','r','a','t']

mySeries = pd.Series(mydata)
print(mySeries)

# mySeriesData = (['samrat','sanjay','bruce'])
mySeriesData = {'author': 'samrat', 'nickname': 'sanjay', 'fav fiction character': 'bruce'}
mySeries2 = pd.Series(mySeriesData)
print(mySeries2)

age = pd.Series([20,21,15], name = "age")
print(age)

# i want to maximum value in age
print('maximum age is :', age.max())
# i want to minimum value in age
print('minimum age is :', age.min())

### it describes the all details in the array 
print(age.describe())

"""The describe() method provides a quick overview of the numerical data in a DataFrame.

💪⚡ A Series, by contrast, is a sequence of data values. If a DataFrame is a table, a Series is a list. And in fact you can create one with nothing more than a list:*italicized text* ⚡

Dataframe --> multi dimensional array
"""

df = pd.DataFrame({
    'Name':['spiderman','ironman','captain america','thor'], 
    'power':['webs','suit','shield','hammer',],
    'Avenger':['yes','yes','yes','yes']
    },
                  index = [10,20,30,40]
                  );
print(df)

### When selecting a single column of a pandas DataFrame, the result is a pandas Series.
### To select the column, use the column label in between square brackets [].

print(df["Name"])

print(df["power"])

### read file from csv file
read_file = pd.read_csv("student.csv")
print(read_file)